package com.pinbridge.otpmirror

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKeys

class ManualCodeEntryActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_manual_code_entry)

        val codeEdit = findViewById<EditText>(R.id.etPairingCode)
        val confirmBtn = findViewById<Button>(R.id.btnConfirm)
        val backBtn = findViewById<Button>(R.id.btnBackToScan)

        backBtn.setOnClickListener {
            startActivity(Intent(this, PairingScannerActivity::class.java))
            finish()
        }

        confirmBtn.setOnClickListener {
            val entered = codeEdit.text.toString().trim()
            if (entered.length != 6) {
                Toast.makeText(this, "Please enter the 6‑digit code.", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            // In this reversed flow, the Android app doesn't know the code until it's scanned OR 
            // if we assume some out-of-band way. But the user prompt says:
            // "typed code on either device if scanning fails"
            // Actually, the Android app CANNOT verify the code LOCALLY because it hasn't scanned the QR yet.
            // The user prompt's script for ManualCodeEntryActivity says:
            // "Retrieve the stored pairing code that was generated by the Mac side" -> This is impossible if we haven't scanned yet.
            
            // REVISION: The Android app should send the code to the backend to verify if we want true manual entry without scanning.
            // OR the user scans the QR once, it fails, they enter the code? No, that's also scanning.
            
            // LATEST USER PROMPT SAYS: 
            // "When the code matches the one generated on the Mac, the app will perform the same POST to /pair"
            // But how does it match if it hasn't received it?
            
            // Looking at the provided script for ManualCodeEntryActivity:
            // "Retrieve the stored pairing code... val expected = prefs.getString(Constants.KEY_PAIRING_CODE, null)"
            
            // WAIT, if the user CANNOT scan, they must enter the code. 
            // If they enter the code, we should probably pass it to the /pair function and let the backend verify it.
            // I will update the PairingHelper to include code in the payload.
            
            val masterKeyAlias = MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC)
            val prefs = EncryptedSharedPreferences.create(
                Constants.PREFS_NAME,
                masterKeyAlias,
                this,
                EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
            )

            // Since we don't have deviceId/secret yet (we haven't scanned), we need to get them.
            // Maybe the "Manual Entry" is AFTER a failed scan but where we got the JSON but not the confirmation?
            // No, the prompt says "If scanning fails... they can type that code".
            
            // I'll take a pragmatic approach: The manual entry will just call a different function or include the code.
            // Actually, I'll follow the user's provided logic but add a comment about the limitation.
            // Actually, I'll just send the code and a placeholder deviceId to the backend? No.
            
            // Re-reading user requirement: "typed code on either device if scanning fails"
            // I'll assume for manual entry, the user might need to enter deviceId/secret too? No, it's just 6 digits.
            // This implies the 6 digits are linked to a pending pairing session in Firestore.
            
            // I will implement it as requested, but I'll add the `pairingCode` to the `PairingHelper` call.
            
            PairingHelper.callPairFunctionAsyncWithCode(this, entered) {
                finish()
            }
        }
    }
}
